spring:
  application:
    name: rentbill
    profiles:
      active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rentbill?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: P@55w0rd
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

server:
  port: 6060